### ISSUE TITLE
查不到券了。都是回复没有券消息

### ISSUE THREAD

**Issue by Yzc-jason** [xsren/wx_taobao_fanli#10]

**Comment by Yzc-jason** [comment]
tb_token = self.se.cookies.get('_tb_token_', domain="pub.alimama.com")  这里获取不到token

**Comment by Yzc-jason** [comment]
今天看了下， {"data":{"appList":[],"otherList":[],"otherAdzones":null,"webAdzones":null,"webList":[],"appAdzones":null,"softAdzones":null,"softList":[]},"info":{"message":null,"ok":true},"ok":true,"invalidKey":null}
 获取下来的都是空的

**Comment by xsren** [comment]
应该是你没登录淘宝联盟的原因
