### ISSUE TITLE
特定商品出现的可复现error

### ISSUE THREAD

**Issue by siyuanxu** [xsren/wx_taobao_fanli#11]
在进行测试的时候，出现一例可复现 error，对其他功能没有影响，但是会阻塞后续消息的处理。

出现 error 的淘口令为：

```
【森马风衣男士简约风景印花休闲中长款外套学生韩版潮】http://v.wzd0.com/h.DRVIuL 点击链接，再选择浏览器打开；或复制这条信息￥YrFL07W19G6￥后打开👉手淘👈
```

在查询这个淘口令对应的联盟信息时，terminal 被以下错误警报，错误信息为
```
2017-11-21 10:49:10,972 get_real_url[line:411] [DEBUG]: https://err.taobao.com/error1.html?c=404&u=https://www.taobao.com/error1.html&r=,502,[]
```
上述错误信息大概20ms 提示一次，阻塞了终端。
不知道是不是转链过程中出现的 bug？

由于能力有限，只能提供这些信息，暂时不能提供 bug 原因。repo 主有兴趣的话可以使用上方淘口令复现一下看看。

**Comment by xsren** [comment]
![image](https://user-images.githubusercontent.com/4971925/33327308-1f675574-d492-11e7-9493-d239095341d3.png)
没有复现错误，在淘宝联盟上测试发现确实是没参加推广

**Comment by siyuanxu** [comment]
感谢回复
- 未能复现的原因应该是淘口令过期，21日的该商品确实参与了联盟推广；
- 可以确定的是，在出现这个问题时，淘宝联盟和微信都处于登录状态，在terminal停止掉不断弹出的信息后一切功能即可正常运行。

不过后来一直没有出现过类似问题。应该是极少数的个例。
