### ISSUE TITLE
二维码加载出现错误

### ISSUE THREAD

**Issue by ws02589111** [xsren/wx_taobao_fanli#16]
直接使用你提交的最新docker镜像, docker.io/xsren/wx_tb_fanli, 启动容器后微信二维码无法加载, 出现
'ascii' codec can't encode characters in position 0-10: ordinal not in range(128)
报错

**Comment by xsren** [comment]
无法重现啊,能贴一下具体的错误吗？

**Comment by ws02589111** [comment]
具体的错误信息就是如上所示,没有更加详细的错误了, 我在使用最新的代码重构镜像之后就正常了, 应该是你的镜像用的是老版本代码导致的

**Comment by xsren** [comment]
谢谢！我重构一下！
