### ISSUE TITLE
淘宝cookie过期问题

### ISSUE THREAD

**Issue by jindx0713** [xsren/wx_taobao_fanli#2]
现在在无任何操作情况下，一个小时左右就会过期

**Comment by xsren** [comment]
这个我看了 确实一个小时左右就过期 但是还没找到方法

**Comment by xsren** [comment]
已解决。加上了一个线程，定期访问淘宝联盟，可以保持session。

**Comment by xiefg** [comment]
淘宝联盟扫码登录后定时访问联盟页面真的可以保持吗，我现在怎么测试都是半小时就退出了

**Comment by xsren** [comment]
@xiefg 之前是可以的，现在貌似不行了，最近比较忙，没时间整这个了。。
