### ISSUE TITLE
post data failure

### ISSUE THREAD

**Issue by 571821151** [xsren/wx_taobao_fanli#4]
在Windows环境中__get_tk_link_s2方法中post数据到http://pub.alimama.com/common/adzone/selfAdzoneCreate.json
返回
'{"data":null,"info":{"message":"页面失效，建议重启浏览器再试！","ok":false},"ok":false,"invalidKey":null}'
求解！

**Comment by xsren** [comment]
一直出现吗？

**Comment by 571821151** [comment]
一直出现，而且__get_tk_link_s1方法中的   adzoneid = rj['data']['otherAdzones'][0]['sub'][0]['id'] 也没有对应的['sub']项。这个get方法是从那个网址抓包取得的呀，求解，我想自己写一遍。。

**Comment by 571821151** [comment]
是否在阿里妈妈需要开通相应的推广位

**Comment by xsren** [comment]
麻烦你把错误堆栈贴一下。
你确认一下，你的账号能分享吗？
