### ISSUE TITLE
偶尔出现死循环

### ISSUE THREAD

**Issue by jindx0713** [xsren/wx_taobao_fanli#6]
【美珍香旗舰店】，复制这条信息￥PEEq0UBjo3q￥后打开👉手机淘宝👈
![wechatimg143](https://user-images.githubusercontent.com/30382973/31601208-afa3ce60-b21e-11e7-8d69-3f43d2d05991.jpeg)

**Comment by xsren** [comment]
没找到店铺相关的接口，不支持分享店铺
