### ISSUE TITLE
登好之后发消息没反应

### ISSUE THREAD

**Issue by powaner** [xsren/wx_taobao_fanli#9]
按您的说明来操作 扫了两个码且登陆成功之后 发送淘口令没反应
Login successfully as 0
Start auto replying.
No uins in 51 message

Tvraceback (most recent call last):
isit_main_url......
  File "C:\Users\C\Desktop\1\libs\wx_bot.py", line 32, in check_if_is_tb_link

2017-10-29 11:41:27
    print msg.text
UnicodeEncodeError: 'gbk' codec can't encode character u'\ud83d' in position 130
: illegal multibyte sequence
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\itchat\components\register.py", line 60, i
n configured_reply
    r = replyFn(msg)
  File "C:\Users\C\Desktop\1\libs\wx_bot.py", line 119, in text_reply
    check_if_is_tb_link(msg)
  File "C:\Users\C\Desktop\1\libs\wx_bot.py", line 111, in check_if_is_tb_lin
k
    ''' % q
UnboundLocalError: local variable 'q' referenced before assignment

**Comment by xsren** [comment]
之前一直在pycharm下开发，今天在win下直接运行会报错，我做了一下兼容，你pull最新的代码试试。

**Comment by powaner** [comment]
好像还是一样 Login successfully as 0
Start auto replying.
[1;37m2017-11-01 00:23:57,880 check_if_is_tb_link[line:38] [DEBUG]: 銆愮幇鍦ㄥ
姞鍏ユ垜鐨勬垬闃燂紝涓€璧风摐鍒?000涓囧ぉ鐚弻11澶х孩I鍖?銆慼ttp://s.odx7.com/
h.FxTbi2 鐐瑰嚮閾炬帴锛屽啀閫夋嫨娴忚鍣ㄦ墦寮€锛涙垨澶嶅埗杩欐潯淇℃伅锟Bq40
TgjPGk锟ュ悗鎵撳紑馃憠鎵嬫窐馃憟[0m
No uins in 51 message

No uins in 51 message

**Comment by xsren** [comment]
看日志应该是成功了

**Comment by powaner** [comment]
可是微信并没有回复？

**Comment by xsren** [comment]
你的发的啥淘口令？我看看

**Comment by powaner** [comment]
【我剁手都要买的宝贝（创易文件盒a4档案盒资料盒塑料文件夹收纳盒定制办公用品批发包邮），快来和我一起瓜分红I包】http://s.odx7.com/h.FMOtN8?sm=adea72 点击链接，再选择浏览器打开；或复制这条信息￥6JyY0gAcqRn￥后打开手淘

**Comment by xsren** [comment]
这个是因为没有对应的匹配规则，回头我加一下。你可以试试这个：

【久丽洗碗布吸水不掉毛加厚竹纤维抹布厨房清洁布不沾油洗碗巾】http://z.apwmu.com/h.FH3VCQ 点击链接，再选择浏览器打开；或复制这条信息￥z9NQ0T2EKp7￥后打开👉手淘👈

**Comment by powaner** [comment]
喔喔 可以了！就是能不能调显示的那个返现比例啊。。。

**Comment by xsren** [comment]
这个你可以自己改一下 我回头把这些抽到配置文件中

**Comment by powaner** [comment]
谢谢！  等您的新消息。这个自己改要怎么弄呢？

**Comment by powaner** [comment]
对了 这个能否自动申请高拥呢？

**Comment by xsren** [comment]
不能

2017-11-01 10:41 GMT+08:00 powaner <notifications@github.com>:

**Comment by siyuanxu** [comment]
@powaner 对回复内容做调整的话需要修改 libs/wx-bot.py 文件中的内容。这里的代码 xsren 写的很明了，可以自行修改。
